# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rec.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'rec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trec.proto\x12\x03rec\"=\n\x0b\x46\x65\x65\x64Request\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"0\n\x0c\x46\x65\x65\x64Response\x12\x10\n\x08post_ids\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\"-\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"0\n\x0cUserResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x32\x7f\n\x0bRecommender\x12\x35\n\x0eGetContentFeed\x12\x10.rec.FeedRequest\x1a\x11.rec.FeedResponse\x12\x39\n\x12GetUserSuggestions\x12\x10.rec.UserRequest\x1a\x11.rec.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDREQUEST']._serialized_start=18
  _globals['_FEEDREQUEST']._serialized_end=79
  _globals['_FEEDRESPONSE']._serialized_start=81
  _globals['_FEEDRESPONSE']._serialized_end=129
  _globals['_USERREQUEST']._serialized_start=131
  _globals['_USERREQUEST']._serialized_end=176
  _globals['_USERRESPONSE']._serialized_start=178
  _globals['_USERRESPONSE']._serialized_end=226
  _globals['_RECOMMENDER']._serialized_start=228
  _globals['_RECOMMENDER']._serialized_end=355
# @@protoc_insertion_point(module_scope)